### ISSUE TITLE
Plugin overrides Command Palette shortcut (Ctrl+Alt+P)

### ISSUE THREAD

**Issue by sascha-wolf** [Governance-com/gearbox-sublime-sencha#1]
As the titel says, the plugin overrides the shortcut for the command palette; at least it does it under windows.

Although a user could fix it by manually remapping the shortcut, that would also need a remapping of the plugins commands and at least for me that's enough reasons to remove the plugin again.

I don't think any plugin should override this shortcut, since the access to the command palette really is essential to sublime.

But that are just my two cents.

**Comment by moghammed** [comment]
Thank you for your feedback! 

I updated the default Windows keymap so the plugin doesn't override the command palette shortcut anymore.
